"use strict";
const assert=require("node:assert/strict"),core=require("../operations-mod/expansion-core");
const ll=(x,y)=>[121.5+x/95500,31.2+y/110540];
function fixture(){
  const rail=(id,a,b,type=null)=>({id,coords:[ll(a,0),ll(b,0)],length:b-a,type,trackType:"pvg-ops-heavy-160",startElevation:-10,endElevation:-10,buildType:"constructed",reversable:true});
  const tracks=[rail("prev1",-1200,-1100,"station"),rail("prev2",-1100,-1000,"station"),rail("in",-1000,0),rail("p1",0,100,"station"),rail("p2",100,200,"station"),rail("out",200,1200),rail("next1",1200,1300,"station"),rail("next2",1300,1400,"station")];
  const node=(id,trackIds)=>({id,trackIds}),a=node("a",["prev1","prev2"]),b=node("b",["p1","p2"]),c=node("c",["next1","next2"]);
  const combo=ids=>({path:ids.map(trackId=>({trackId,reversed:false}))});
  return {tracks,trackGroups:[],routes:[{id:"local",stNodes:[a,b,c],stCombos:[combo(["prev1","prev2","in","p1","p2"]),combo(["p1","p2","out","next1","next2"])]}],trains:[],signals:[],timeConfig:{elapsedSeconds:100}};
}
const emptyOutline={type:"Polygon",coordinates:[[ll(5000,5000),ll(5100,5000),ll(5100,5100),ll(5000,5100),ll(5000,5000)]]};
const options={id:"test-expansion",exclusionGeometries:[emptyOutline],minimumRadius:600};
let state=fixture(),before=structuredClone(state),plan=core.planBypass(state,"local","b",options);
assert.deepEqual(state,before);assert.equal(plan.tracks.length,1);assert.equal(plan.tracks[0].pvgRole,"express-bypass");
assert.deepEqual(plan.tracks[0].coords[0],state.tracks.find(t=>t.id==="in").coords[0]);
assert.deepEqual(plan.tracks[0].coords.at(-1),state.tracks.find(t=>t.id==="out").coords.at(-1));
assert.ok(plan.geometry.minimumRadius>=606);assert.ok(plan.geometry.maximumTurnDegrees<=3);
assert.ok(plan.affectedTrackIds.includes("p1"));
assert.throws(()=>core.planBypass(state,"local","a",options));
assert.throws(()=>core.planBypass(state,"local","b",{...options,exclusionGeometries:[]}));
assert.throws(()=>core.planBypass(state,"local","b",{...options,exclusionGeometries:[{type:"Polygon",coordinates:[[ll(-2000,-50),ll(2000,-50),ll(2000,50),ll(-2000,50),ll(-2000,-50)]]}]}));
state.trackGroups=plan.trackGroups;assert.throws(()=>core.planBypass(state,"local","b",options));
state=fixture();state.trains=[{id:"x",windows:{warning:{tracks:[{trackId:"in"}]}}}];
assert.equal(core.vacant(state,plan.affectedTrackIds),false);state.trains=[];
state.signals=[{signalTracks:[{trackId:"out"}],status:{reservedBy:{trainId:"x",timeVerified:100}}}];
assert.equal(core.vacant(state,plan.affectedTrackIds),false);
state.signals[0].status.reservedBy.timeVerified=98;assert.equal(core.vacant(state,plan.affectedTrackIds),false,"native reservations cannot be aged out to permit construction");
state.signals[0].status.occupations=[state.signals[0].status.reservedBy];state.signals[0].status.reservedBy=null;
assert.equal(core.vacant(state,plan.affectedTrackIds),true,"old occupation history alone is not a present reservation");
const old={id:"old",type:"v-merge",buildType:"constructed",signalTracks:[{trackId:"in",areaCovered:"all"}],status:{occupations:[{trainId:"x",timeVerified:100}],reservedBy:{trainId:"y",timeVerified:100}}};
const fresh={...old,id:"fresh",status:{occupations:[],reservedBy:null}};
let preserved=core.preserveSignals([old],[fresh],["in"]);assert.equal(preserved[0],old);assert.equal(preserved.length,1);
preserved=core.preserveSignals([old],[{...fresh,signalTracks:[...fresh.signalTracks,{trackId:"new",areaCovered:"all"}]}],["in","new"]);
assert.ok(preserved.includes(old),"existing route signal identity and occupation must survive a changed merge");
const changed={...fresh,id:old.id,signalTracks:[...old.signalTracks,{trackId:"new",areaCovered:"all"}]};
assert.throws(()=>core.preserveSignals([old],[changed],["in","new"]),/范围之外/);
preserved=core.preserveSignals([old],[changed],["in","new"],["in","new"]);
assert.equal(preserved.length,2);assert.ok(preserved.includes(old));assert.notEqual(preserved[0].id,old.id);
assert.equal(preserved[0].status,changed.status);assert.equal(old.status.occupations[0].trainId,"x");
assert.equal(core.preserveSignals([old],[changed],["in","new"],["in","new"])[0].id,preserved[0].id,"deterministic new physical resource identity");
assert.deepEqual(core.preserveSignals([old],[{...old,signalTracks:[{trackId:"unrelated",areaCovered:"all"}]}],["in","unrelated","new"],["new"]),[old],"global regeneration cannot alter an unrelated signal identity/occupation");
assert.deepEqual(core.preserveSignals([old],[changed],["in"],[]),[old],"removing only owned rails retains the exact original signals");
assert.equal(core.preserveSignals([old],[],[]).length,0,"removing unused own rails cannot retain nonexistent coverage");
console.log(JSON.stringify({ok:true,geometry:plan.geometry,scope:"own-code automatic connected blueprint and continuity guard units; not native construction"}));
module.exports={fixture,options};
