#!/usr/bin/env node
"use strict";
const assert = require("node:assert/strict");
const { performance } = require("node:perf_hooks");
require("./test_operations_mod.js");
const mod = global.__PVG_OPERATIONS__, state = global.__PVG_OPERATIONS_TEST_STATE__;
const type = "pvg-ops-medium-120";
function fixture(count = 10) {
  const nodes = Array.from({ length: count }, (_, i) => ({ id: "n" + i, center: [121 + i / 100, 31], trackIds: ["t" + i] }));
  state.tracks = nodes.map((node, i) => ({ id: "t" + i, length: 1000, trackType: type, coords: [node.center, [node.center[0] + .01, 31]] }));
  state.trackGroups = nodes.map((node, i) => ({ id: "tg" + i, trackLanesType: "parallel", trackIds: ["t" + i] }));
  state.stations = nodes.map((node, i) => ({ id: "s" + i, stNodeIds: [node.id], trackIds: ["t" + i], trackGroupId: "tg" + i, maxCars: 6, name: "站" + i }));
  state.stationGroups = state.stations.map((s, i) => ({ id: "sg" + i, stationIds: [s.id], name: s.name, center: nodes[i].center }));
  state.routes = [{ id: "base", bullet: "原线", trainType: type, carsPerTrain: 4, stNodes: [...nodes, ...nodes.slice(0, -1).reverse()],
    stCombos: nodes.slice(1).map((node, i) => ({ path: [{ trackId: "t" + i }], distance: 1000 })), stComboTimings: [{ arrivalTime: 0 }, { arrivalTime: 3600 }], trainSchedule: { highDemand: 2 } }];
  state.trains = [{ id: "original-train", routeId: "base", motion: { speed: 14 }, passengers: ["p1"] }];
  state.ownedCarsByType = { [type]: 1000 }; state.money = 1e10;
  state.previewRoute = null; state.timeConfig = { paused: false, elapsedSeconds: 400 };
  state.setTimeConfig = function (partial) { this.timeConfig = { ...this.timeConfig, ...partial }; };
  state.setPreviewRoute = function (route) { this.previewRoute = route; this.timeConfig = { ...this.timeConfig, paused: true }; };
  state.deleteTrain = function (id) { this.trains = this.trains.filter((train) => train.id !== id); };
  state.deleteRoute = function (id) { this.routes = this.routes.filter((route) => route.id !== id); };
  state.setStations = function (stations) { this.stations = stations; };
  state.setOwnedTrainCount = function (count) { this.ownedTrainCount = count; };
  state.buyTrains = function (count, trainType) { this.money -= count * mod.trainProfiles.find((p) => p.id === trainType).carCost; this.ownedCarsByType[trainType] += count; return { success: true }; };
  state.confirmRouteChange = function () {
    if (this.failConfirm) return { success: false };
    const route = { ...this.routes.find((r) => r.id === this.previewRoute.id), stNodes: this.previewRoute.stNodes };
    route.stCombos = route.stNodes.slice(1).map((node, i) => ({ startStNodeId: route.stNodes[i].id, endStNodeId: node.id, path: [{ trackId: "t0" }], distance: 1000 }));
    route.stComboTimings = [{ arrivalTime: 0 }, { arrivalTime: 1800 }];
    this.setRoutes(this.routes.map((r) => r.id === route.id ? route : r));
    this.setPreviewRoute(null); return { success: true };
  };
  return nodes;
}
let nodes = fixture();
let plan = mod.planRouteStations("base", "rapid", "medium");
assert.equal(plan.stations.at(-1).terminal, true);
assert.ok(plan.recommendedStops.includes(9));
const selected = plan.recommendedStops.map((i) => state.routes[0].stNodes[i].id);
assert.deepEqual(selected, [...selected].reverse(), "both directions share physical stop selection");
assert.equal(plan.stations[0].trackCount, 2);
assert.equal(mod.planRouteStations("base", "rapid", "medium"), plan, "unchanged topology reuses a plan");
state.trains = state.trains.map((train) => ({ ...train, motion: { speed: 20 } }));
assert.equal(mod.planRouteStations("base", "rapid", "medium"), plan, "simulation movement does not rebuild the planner");
state.routes = [...state.routes, { ...state.routes[0], id: "fast" }, { ...state.routes[0], id: "express" }];
plan = mod.planRouteStations("base", "local", "medium");
assert.ok(plan.stations.every((s) => s.routeCount === 1 && s.trackCount === 2), "service variants cannot create fake eight-track hubs");
state.stations = state.stations.map((s) => ({ ...s, maxCars: 2 }));
assert.equal(mod.fleetAdvice("base", type).success, false, "short platforms block long rolling stock");
nodes = fixture();
mod.installNonstopPlanning();
state.setPreviewRoute(state.routes[0]); assert.equal(state.timeConfig.paused, false);
state.setTimeConfig({ paused: true }); state.setPreviewRoute({ ...state.routes[0] }); assert.equal(state.timeConfig.paused, true);
state.setPreviewRoute(null); assert.equal(state.timeConfig.paused, true, "closing the editor respects an explicit pause");
state.setTimeConfig({ paused: false });
const beforeTrain = state.trains[0], beforeRoute = state.routes[0], beforeMoney = state.money;
let result = mod.applyRouteDesign("base", "medium", "rapid");
assert.equal(result.success, true, JSON.stringify(result));
assert.equal(state.routes[0], beforeRoute); assert.equal(state.trains[0], beforeTrain);
assert.equal(state.timeConfig.paused, false); assert.equal(state.money, beforeMoney);
assert.equal(state.routes.length, 2); assert.ok(state.routes[1].stCombos.length > 0);
assert.ok(state.stations[0].pvgAutomaticRole.owners[result.serviceRouteId]);
assert.equal(state.stations[0].stationType, "pvg-ops-local-station");
assert.deepEqual(state.routes[1].stNodes.map((node) => node.id), selected);
assert.equal(mod.applyRouteDesign("base", "medium", "rapid").success, false, "double click cannot duplicate a service");
const serialized = JSON.parse(JSON.stringify(state.routes[1]));
state.routes = [state.routes[0], serialized];
assert.equal(mod.undoRouteDesign(serialized.id).success, true, "undo survives save serialization");
assert.equal(state.routes.length, 1); assert.equal(state.trains[0], beforeTrain);
assert.equal(state.stations[0].stationType, undefined);
assert.equal(state.stations[0].pvgAutomaticRole, undefined, "undo restores automatically managed station roles");
assert.equal(Object.prototype.hasOwnProperty.call(state.stations[0], "stationType"), false);
state.failConfirm = true;
assert.equal(mod.applyRouteDesign("base", "medium", "express").success, false);
assert.equal(state.routes.length, 1); assert.equal(state.previewRoute, null); assert.equal(state.timeConfig.paused, false);
state.failConfirm = false;
state.ownedCarsByType[type] = 0;
result = mod.applyRouteDesign("base", "medium", "express");
assert.equal(result.success, true); assert.equal(result.activeTrains, 0);
const id = result.serviceRouteId;
const advice = mod.fleetAdvice(id, type, { excludeRouteId: id });
assert.equal(mod.purchaseServiceFleet(id, advice.purchaseCost + 1).success, false, "stale quotes must not spend money");
const money = state.money;
assert.equal(mod.purchaseServiceFleet(id, advice.purchaseCost).success, true);
assert.equal(state.routes.find(r=>r.id===id).pvgPendingDeparture,true,"explicit fleet purchase enables safe pending departure checks");
assert.equal(money - state.money, advice.purchaseCost);
const owned = state.ownedCarsByType[type];
assert.equal(mod.undoRouteDesign(id).success, true); assert.equal(state.ownedCarsByType[type], owned);
assert.equal(state.money, money - advice.purchaseCost, "undo never fabricates a refund");
result = mod.applyRouteDesign("base", "medium", "rapid");
state.routes = state.routes.map((r) => r.id === result.serviceRouteId ? { ...r, carsPerTrain: 6 } : r);
assert.equal(mod.undoRouteDesign(result.serviceRouteId).success, false, "later edits are never overwritten");
nodes = fixture();
const partner = { ...state.routes[0], id: "partner", bullet: "接续线", stNodes: [nodes[9], { id: "p1", center: [121.11, 31] }, { id: "p2", center: [121.12, 31] }, { id: "p1", center: [121.11, 31] }, nodes[9]], stCombos: [{ path: [{ trackId: "t9" }] }] };
state.routes = [...state.routes, partner];
assert.equal(mod.throughCandidates("base", type).length, 1);
const through = mod.serviceStopSequence("base", "medium", "express", "partner");
assert.equal(through.success, true); assert.ok(through.nodes.some((node) => node.id === "p2"));
assert.equal(through.nodes[0].id, through.nodes.at(-1).id);
result = mod.applyRouteDesign("base", "medium", "express", { throughRouteId: "partner" });
assert.equal(result.success, true); assert.equal(state.routes.at(-1).pvgOperatingMode, "express");
assert.equal(state.routes.at(-1).pvgThroughRouteId, "partner");
assert.equal(state.routes[1], partner);
assert.equal(mod.planRouteStations("base", "local", "medium").stations[0].routeCount, 1, "a through service must not invent a second corridor at every original stop");
assert.equal(mod.throughCandidates("base", type).some((item) => item.routeId === result.serviceRouteId), false, "a through child cannot become its parent's new partner");
mod.undoRouteDesign(result.serviceRouteId);
const map = { sources: {}, layers: {}, addSource(id, definition) { this.sources[id] = { ...definition, setData(data) { this.data = data; } }; }, getSource(id) { return this.sources[id]; }, removeSource(id) { delete this.sources[id]; }, addLayer(definition) { this.layers[definition.id] = definition; }, getLayer(id) { return this.layers[id]; }, removeLayer(id) { delete this.layers[id]; }, fitBounds() {} };
window.SubwayBuilderAPI.utils.getMap = () => map;
assert.equal(mod.showPlanPreview("base", "express", "medium", "partner").success, true);
assert.equal(Object.keys(map.sources).length, 1); assert.equal(Object.keys(map.layers).length, 3);
assert.deepEqual(map.sources["pvg-operation-preview"].data.features.find((f) => f.geometry.type === "LineString").geometry.coordinates, state.tracks[0].coords);
mod.clearPlanPreview(); assert.equal(Object.keys(map.sources).length, 0);
state.ownedCarsByType = { "pvg-ops-metro-local-80": 12, "pvg-ops-light-80": 3, "pvg-ops-metro-express-120": 20 };
state.ownedTrainCount = 35;
assert.equal(mod.migrateLegacyInventory().cars, 32);
assert.equal(state.ownedCarsByType["pvg-ops-light-80"], 15);
assert.equal(state.ownedCarsByType["pvg-ops-medium-120"], 20);
assert.equal(mod.migrateLegacyInventory().changed, 0, "inventory conversion cannot duplicate owned cars");
assert.equal(state.ownedTrainCount, 35);

// Native default station types must round-trip, even with overlapping service
// claims or a later manual edit. Undo must not leave orphan ownership records.
fixture();
state.stations = state.stations.map((station) => ({ ...station, stationType: "standard" }));
const rapid = mod.applyRouteDesign("base", "medium", "rapid", { headwayMinutes: 11 });
const express = mod.applyRouteDesign("base", "medium", "express");
assert.ok(rapid.success && express.success);
assert.equal(state.routes.find((route) => route.id === rapid.serviceRouteId).pvgHeadwayMinutes, 11);
const managedPlan = mod.planRouteStations(express.serviceRouteId, "express", "medium");
assert.equal(managedPlan.stations.length, 10, "applied services still show skipped physical stations");
assert.equal(mod.serviceStopSequence(express.serviceRouteId, "medium", "express").nodes.length, state.routes.find((r) => r.id === express.serviceRouteId).stNodes.length, "do not skip stops a second time");
assert.ok(managedPlan.stations.filter((station) => station.role === "overtake").every((station) => station.needsConstruction), "missing bypass tracks are visibly pending");
assert.ok(state.stations[0].pvgAutomaticRole.owners[rapid.serviceRouteId]);
assert.ok(state.stations[0].pvgAutomaticRole.owners[express.serviceRouteId]);
assert.equal(mod.undoRouteDesign(rapid.serviceRouteId).success, true);
assert.equal(state.stations[0].stationType, "pvg-ops-local-station");
assert.equal(mod.undoRouteDesign(express.serviceRouteId).success, true);
assert.ok(state.stations.every((station) => station.stationType === "standard" && !station.pvgAutomaticRole));
result = mod.applyRouteDesign("base", "medium", "rapid");
state.stations = state.stations.map((station, i) => i === 0 ? { ...station, stationType: "manual-station-type" } : station);
assert.equal(mod.undoRouteDesign(result.serviceRouteId).success, true);
assert.equal(state.stations[0].stationType, "manual-station-type", "manual station types survive undo");
assert.equal(state.stations[0].pvgAutomaticRole, undefined, "manual edits do not leave orphan service owners");

// With the original endpoint occupied, rotate only the new closed service to
// a free terminal. Its directed stop edges and original trains stay intact.
fixture();
const desiredCycle = mod.serviceStopSequence("base", "medium", "express").nodes;
state.trains[0].windows = { train: { tracks: [{ trackId: "t0" }] } };
const occupiedTrain = state.trains[0];
result = mod.applyRouteDesign("base", "medium", "express");
assert.equal(result.success, true);
const rotatedCycle = state.routes.find((route) => route.id === result.serviceRouteId).stNodes;
const edges = (sequence) => sequence.slice(1).map((node, i) => sequence[i].id + ">" + node.id).sort();
assert.equal(rotatedCycle[0].id, "n9");
assert.deepEqual(edges(rotatedCycle), edges(desiredCycle), "rotation cannot invent a connection or remove a stop");
assert.equal(state.trains[0], occupiedTrain);
assert.equal(state.routes[0].stNodes[0].id, "n0");
assert.ok(result.warnings.some((warning) => warning.includes("原起点被占用")));
assert.equal(mod.undoRouteDesign(result.serviceRouteId).success, true);

// The read-only departure chooser used by native QA is the same production
// implementation. It cannot clear occupied platforms or mutate the stop list.
fixture();
const pending=mod.serviceStopSequence("base","medium","express");
const chooserBefore=JSON.stringify(pending);
state.trains[0].windows={train:{tracks:[{trackId:"t0"}]}};
const freeDeparture=mod.chooseFreeDeparture(state,pending);
assert.equal(freeDeparture.changed,true);
assert.deepEqual(edges(freeDeparture.nodes),edges(pending.nodes));
assert.equal(JSON.stringify(pending),chooserBefore);
state.trains[0].windows.train.tracks.push({trackId:"t9"});
assert.equal(mod.chooseFreeDeparture(state,pending).changed,false,"no free terminal means wait for native dispatch, never force placement");
state.trains[0].windows.train.tracks=[];
state.signals=[{signalTracks:[{trackId:"t0"}],status:{occupations:[],reservedBy:{trainId:state.trains[0].id,timeVerified:state.timeConfig.elapsedSeconds}}}];
const reservedBefore=JSON.stringify(state.signals);
assert.equal(mod.chooseFreeDeparture(state,pending).changed,true,"an approaching train's fresh reservation blocks the original endpoint");
assert.equal(JSON.stringify(state.signals),reservedBefore,"choosing a departure cannot clear native claims");
state.signals[0].status.reservedBy.timeVerified=state.timeConfig.elapsedSeconds-2;
assert.equal(mod.chooseFreeDeparture(state,pending).changed,true,"native reservations do not expire by the chooser's age heuristic");
state.signals[0].status.occupations=[state.signals[0].status.reservedBy];
state.signals[0].status.reservedBy=null;
assert.equal(mod.chooseFreeDeparture(state,pending).changed,false,"stale occupation history alone does not prove present occupancy");
state.signals=[];

// Both endpoints can be busy at creation, then one becomes free later. Only
// the owned zero-fleet service may retry; never move or reset original trains.
fixture();
state.trains[0].windows={train:{tracks:[{trackId:"t0"},{trackId:"t9"}]}};
result=mod.applyRouteDesign("base","medium","express");
assert.equal(result.success,true);
const waitingId=result.serviceRouteId,originals=[...state.trains],originalRoute=state.routes[0],originalClock={...state.timeConfig};
let waiting=state.routes.find(r=>r.id===waitingId),waitingEdges=edges(waiting.stNodes);
assert.equal(waiting.stNodes[0].id,"n0");
assert.equal(waiting.pvgPendingDeparture,true);
assert.deepEqual(mod.retryServiceDeparture(waitingId),{success:true,pending:true,changed:false});
const checkPending=global.__PVG_TEST_INTERVALS__.get(window.__PVG_PENDING_DEPARTURE_WATCH__);
assert.equal(typeof checkPending,"function","map-ready must install a real pending-departure watcher");
checkPending();
assert.equal(mod.pendingDepartureStatus().lastChecks.at(-1).changed,false);
state.trains[0].windows.train.tracks=[{trackId:"t0"}];
waiting=JSON.parse(JSON.stringify(waiting));
state.routes=[originalRoute,waiting];
checkPending();
const retried=mod.pendingDepartureStatus().lastChecks.at(-1);
assert.equal(retried.success,true);assert.equal(retried.changed,true);
waiting=state.routes.find(r=>r.id===waitingId);
assert.equal(waiting.stNodes[0].id,"n9");
assert.deepEqual(edges(waiting.stNodes),waitingEdges);
assert.equal(waiting.pvgServiceTransaction.baseline,mod.serviceFingerprint(waiting));
assert.equal(state.routes[0],originalRoute);
assert.deepEqual(state.trains,originals);assert.equal(state.trains[0],originals[0]);
assert.deepEqual(state.timeConfig,originalClock,"pending retry cannot pause, tick, or advance the original network");
assert.equal(state.previewRoute,null);
assert.equal(mod.retryServiceDeparture(waitingId).changed,false,"a currently free endpoint is not rotated again");
// An actual native train, including a transition child, ends auto-selection.
const child={...waiting,id:"pending-child",tempParentId:waitingId};
state.routes.push(child);state.trains.push({id:"native-child-train",routeId:child.id});
assert.deepEqual(mod.retryServiceDeparture(waitingId),{success:true,pending:false,changed:false});
assert.equal(state.routes.find(r=>r.id===waitingId).pvgPendingDeparture,false);
assert.equal(state.routes.at(-1),child);
assert.equal(mod.undoRouteDesign(waitingId).success,true,"retry refreshes the undo receipt without losing ownership");
assert.equal(state.trains[0],originals[0]);

fixture();
result=mod.applyRouteDesign("base","medium","express");
const guardedId=result.serviceRouteId;
waiting=state.routes.find(r=>r.id===guardedId);
state.routes=state.routes.map(r=>r.id===guardedId?{...r,carsPerTrain:6}:r);
const editedRoutes=state.routes;
assert.equal(mod.retryServiceDeparture(guardedId).success,false,"a later player edit stops pending auto-selection");
assert.equal(state.routes,editedRoutes);assert.equal(state.previewRoute,null);
state.routes=state.routes.map(r=>r.id===guardedId?waiting:r);
const foreignDraft={id:"foreign-draft"};state.previewRoute=foreignDraft;
assert.equal(mod.retryServiceDeparture(guardedId).changed,false);
assert.equal(state.previewRoute,foreignDraft,"an open native editor is never overwritten");
state.previewRoute=null;state.timeConfig.paused=true;
assert.equal(mod.retryServiceDeparture(guardedId).changed,false);assert.equal(state.timeConfig.paused,true);
state.timeConfig.paused=false;state.loadingState={status:"loading"};
assert.equal(mod.retryServiceDeparture(guardedId).changed,false);
state.loadingState=[{type:"map",status:"loaded"},{type:"buildingIndex",status:"loading"}];
assert.equal(mod.retryServiceDeparture(guardedId).blockedBy,"loading","native loading state is a list, not a single status object");
state.loadingState=null;
state.pendingStNodeChanges=[{id:"native-edit"}];
assert.equal(mod.retryServiceDeparture(guardedId).changed,false);state.pendingStNodeChanges=[];
state.trains[0].windows={train:{tracks:[{trackId:"t0"}]}};
state.failConfirm=true;
const failedRoutes=state.routes;
assert.equal(mod.retryServiceDeparture(guardedId).success,false);
assert.equal(state.routes,failedRoutes);assert.equal(state.previewRoute,null);
assert.equal(state.timeConfig.paused,false);
state.failConfirm=false;
const pendingNativeConfirm=state.confirmRouteChange;
state.confirmRouteChange=()=>{throw Error("native test error");};
assert.throws(()=>mod.retryServiceDeparture(guardedId),/native test error/);
assert.equal(state.previewRoute,null,"native exceptions cannot leave a pending preview behind");
assert.equal(state.timeConfig.paused,false);
checkPending();
assert.equal(state.routes.find(r=>r.id===guardedId).pvgPendingDeparture,false,"a native exception disables retries instead of spamming the editor");
state.confirmRouteChange=pendingNativeConfirm;
waiting={...waiting,pvgPendingDeparture:true,trainSchedule:{highDemand:0},idealTrainCount:0};
waiting.pvgServiceTransaction={...waiting.pvgServiceTransaction,baseline:mod.serviceFingerprint(waiting)};
state.routes=state.routes.map(r=>r.id===guardedId?waiting:r);
assert.equal(mod.retryServiceDeparture(guardedId).pending,false,"zero-capacity services stop retrying until explicit fleet purchase");

// A saturated shared corridor must reject spending before native purchase.
fixture();
state.ownedCarsByType[type] = 0;
result = mod.applyRouteDesign("base", "medium", "express");
const capacityId = result.serviceRouteId, capacityBefore = state.money;
const capacityQuote = mod.fleetAdvice(capacityId, type, { excludeRouteId: capacityId });
const nativeConfirm = state.confirmRouteChange;
state.confirmRouteChange = function () {
  const answer = nativeConfirm.call(this);
  this.routes = this.routes.map((route) => route.id === capacityId ? { ...route, trainSchedule: { highDemand: 0, mediumDemand: 0, lowDemand: 0, veryLowDemand: 0 } } : route);
  return answer;
};
assert.equal(mod.purchaseServiceFleet(capacityId, capacityQuote.purchaseCost).success, false);
assert.equal(state.money, capacityBefore); assert.equal(state.ownedCarsByType[type], 0);
assert.equal(mod.undoRouteDesign(capacityId).success, true, "capacity rejection restores an undoable service");
fixture();
state.routes = [...state.routes, { ...state.routes[0], id: "temporary", tempParentId: "base" }];
state.trains = [1, 2, 3].map((i) => ({ id: "temp-train-" + i, routeId: "temporary" }));
assert.equal(mod.fleetAdvice("base", type).availableCars, 988, "transition trains reserve real inventory under their parent route");

// The previous benchmark used no route stations and therefore missed the
// expensive planning path. Exercise real station lookup and 200 route lists.
nodes = fixture(5000);
state.routes = Array.from({ length: 200 }, (_, r) => ({ ...state.routes[0], id: "r" + r, stNodes: [...nodes.slice(r * 20, r * 20 + 100), ...nodes.slice(r * 20, r * 20 + 99).reverse()], stCombos: [{ path: [{ trackId: "t" + r }] }] }));
const started = performance.now();
for (let r = 0; r < 200; r++) assert.equal(mod.planRouteStations("r" + r, "express", "medium").success, true);
const allPlansMs = performance.now() - started;
const cached = performance.now();
for (let i = 0; i < 1000; i++) mod.planRouteStations("r199", "express", "medium");
const cached1000Ms = performance.now() - cached;
assert.ok(allPlansMs < 2000, "cold planning 200 routes: " + allPlansMs);
assert.ok(cached1000Ms < 100, "cached preview: " + cached1000Ms);
console.log(JSON.stringify({ ok: true, tests: "physical-stops, families, pause, native-apply, rollback, serialized-undo, station-ownership, manual-edit-protection, pending-departure-retry, capacity-before-purchase, temporary-train-inventory, through-express, map, planning-performance", stations: 5000, routes: 200, allPlansMs, cached1000Ms }, null, 2));
